version: '3'

services:
  web-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - ../..:/workspaces:cached

    # Prevent container from exiting
    command: sleep infinity

    networks:
      - rails_network
    
    environment:
      DB_HOST: web-postgres
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_NAME: naturio_development
      RAILS_ENV: development

    depends_on:
      - web-postgres
      - sonar-server

  web-postgres:
    image: postgres:15
    restart: unless-stopped
    networks:
      - rails_network
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./create-db-user.sql:/docker-entrypoint-initdb.d/create-db-user.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: naturio_development

  sonar-server:
    image: sonarqube:community
    container_name: sonarqube
    restart: unless-stopped
    networks:
      - rails_network
    ports:
      - "9000:9000"
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonar-postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    depends_on:
      - sonar-postgres

  sonar-postgres:
    image: postgres:15
    container_name: sonar-postgres
    restart: unless-stopped
    networks:
      - rails_network
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - sonar-db:/var/lib/postgresql

volumes:
  sonar-db:

networks:
  rails_network:
    driver: bridge
